# fly.toml app configuration file generated for message-board-vy on 2023-10-05T11:44:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "message-board-vy"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
